#!/usr/bin/env bash
# Create Prompt Pack Script
#
# Creates a new prompt pack from the full superpower workflow template.
# Ensures proper integration of all superpower skills and workflow steps.
#
# Usage:
#   ./create-prompt-pack.sh <epic-name> "<Epic Title>" "<brief-description>"
#
# Example:
#   ./create-prompt-pack.sh user-authentication "User Authentication" "Implement OAuth2 login flow"

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TEMPLATE_FILE="$SCRIPT_DIR/prompt-packs/TEMPLATE-full-superpower-workflow.json"
PACKS_DIR="$SCRIPT_DIR/prompt-packs"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

log_info() {
    echo -e "${GREEN}[INFO]${NC} $1"
}

log_warn() {
    echo -e "${YELLOW}[WARN]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# Check if template exists
if [ ! -f "$TEMPLATE_FILE" ]; then
    log_error "Template file not found: $TEMPLATE_FILE"
    exit 1
fi

# Parse arguments
if [ $# -lt 3 ]; then
    log_error "Usage: $0 <epic-name> \"<Epic Title>\" \"<brief-description>\""
    echo ""
    echo "Example:"
    echo "  $0 user-authentication \"User Authentication\" \"Implement OAuth2 login flow\""
    echo ""
    echo "This will create: $PACKS_DIR/roundtable-user-authentication.json"
    exit 1
fi

EPIC_NAME="$1"
EPIC_TITLE="$2"
EPIC_DESCRIPTION="$3"

# Validate epic name (alphanumeric, hyphens, underscores only)
if [[ ! "$EPIC_NAME" =~ ^[a-z0-9_-]+$ ]]; then
    log_error "Epic name must be lowercase alphanumeric with hyphens/underscores only"
    exit 1
fi

OUTPUT_FILE="$PACKS_DIR/roundtable-$EPIC_NAME.json"

# Check if file already exists
if [ -f "$OUTPUT_FILE" ]; then
    log_warn "Prompt pack already exists: $OUTPUT_FILE"
    read -p "Overwrite? (y/N): " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        log_info "Aborted"
        exit 0
    fi
fi

# Get current date
CURRENT_DATE=$(date +%Y-%m-%d)

# Create prompt pack from template
log_info "Creating prompt pack: $OUTPUT_FILE"
log_info "  Epic: $EPIC_NAME"
log_info "  Title: $EPIC_TITLE"
log_info "  Description: $EPIC_DESCRIPTION"

# Use jq to create the prompt pack from template
jq -n \
    --arg epic "$EPIC_NAME" \
    --arg title "$EPIC_TITLE" \
    --arg desc "$EPIC_DESCRIPTION" \
    --arg date "$CURRENT_DATE" \
    '{
        "_comment": "Generated by create-prompt-pack.sh on \($date)",
        "_workflow": "sp-brainstorming → sp-writing-plans → /plan-to-beads → /response-awareness → review → commit",
        "id": "roundtable-\($epic)",
        "title": "\($title): \($desc)",
        "id_prefixes": ["roundtable-\($epic)."],
        "base_prefix": "Active plan: roundtable-\($epic) (\($desc)). Start by checking Agent Mail and any pending /unblock actions.",
        "supervisor": {
            "extra": "Keep everyone on the epic (roundtable-\($epic).*). Prefer /broadcast-targeted (draft). **NEW FEATURES**: Use sp-brainstorming before sp-writing-plans for design exploration. **CONVERSION**: Use /plan-to-beads docs/plans/<plan>.md to automatically convert plans to beads before assigning. Close beads only after reviewer sign-off. For complex epic-level decisions, use ultrathink."
        },
        "reviewer": {
            "extra": "Verify with the bead'\''s target test commands and re-open with concrete diffs if needed. **RECEIPT VERIFICATION REQUIRED**: Before approving, check that implementor provided a receipt (summary of changes, files modified, tests run). Verify receipt matches actual changes with git status and git diff. No receipt = re-open with feedback. **GUARDRAILS ACTIVE**: Filesystem guardrails block git commit/push/merge/rebase - use bd close to approve, bd reopen for feedback. Reviewer role is QA-only, not implementation. See docs/agents.md '\''Reviewer Guardrails'\'' section. For complex analysis, use ultrathink. **SKILLS**: Use sp-verification-before-completion for thorough quality gates."
        },
        "implementor_1": {
            "label_preferences": ["site", "frontend", "ux", "docs", "\($epic)"],
            "reserve_paths_hint": "apps/site/** and docs/** (only what you touch)",
            "test_commands": ["pnpm --filter @roundtable/site test", "pnpm --filter @roundtable/site build"],
            "extra": "CRITICAL: When implementing beads, ALWAYS start with /response-awareness '\''Implement bead [id]: [title]'\'' - this enables metacognitive orchestration and proper skill selection. **SUPERPOWER WORKFLOW**: 1) /response-awareness for implementation, 2) sp-test-driven-development for test-first approach, 3) sp-systematic-debugging if blocked, 4) sp-verification-before-completion before closing. **RECEIPT REQUIRED**: When closing bead, provide a receipt summarizing: files modified, tests run with results, changes summary, and any deviations from plan. Send receipt via Agent Mail or include in bd close message. No receipt = reviewer will re-open."
        },
        "implementor_2": {
            "label_preferences": ["backend", "api", "db", "shared", "\($epic)"],
            "reserve_paths_hint": "apps/backend/** and packages/shared/** (only what you touch)",
            "test_commands": ["pnpm --filter backend test", "pnpm --filter @roundtable/shared test"],
            "extra": "CRITICAL: When implementing beads, ALWAYS start with /response-awareness '\''Implement bead [id]: [title]'\'' - this enables metacognitive orchestration and proper skill selection. **BACKEND PATTERN**: Follow service layer architecture: Routes (HTTP) → Services (Business Logic) → Repositories (Data Access). NEVER write raw SQL in routes. See docs/maf/backend-patterns.md for complete guide. **SUPERPOWER WORKFLOW**: 1) /response-awareness for implementation, 2) sp-test-driven-development for test-first approach, 3) sp-systematic-debugging if blocked, 4) sp-verification-before-completion before closing. **RECEIPT REQUIRED**: When closing bead, provide a receipt summarizing: files modified, tests run with results, changes summary, and any deviations from plan. Send receipt via Agent Mail or include in bd close message. No receipt = reviewer will re-open."
        },
        "guardrails": [
            "Do not run git commit/push/merge/rebase (use bd close for approval)",
            "Reserve only the paths you will touch before editing (reason=<bead-id>)",
            "TDD-first: write the failing test before implementation changes",
            "Keep changes DRY/YAGNI; small diffs; green tests before closing the bead",
            "RECEIPT ENFORCEMENT: No receipt = no close. Implementors must provide receipt, reviewers must verify.",
            "REVIEWER GUARDRAILS: Reviewer cannot git commit/push/merge/rebase - QA-only role, see docs/agents.md",
            "SUPERPOWER WORKFLOW: Always use /response-awareness for bead implementation, not direct coding",
            "FILE RESERVATIONS: Always use file_reservation_paths before editing files",
            "SERVICE LAYER: Backend code must follow Routes → Services → Repositories pattern"
        ]
    }' > "$OUTPUT_FILE"

if [ $? -eq 0 ]; then
    log_info "✅ Prompt pack created successfully: $OUTPUT_FILE"
    echo ""
    echo "Next steps:"
    echo "  1. Review and customize the prompt pack: nano $OUTPUT_FILE"
    echo "  2. Update label_preferences for each implementor based on epic needs"
    echo "  3. Update test_commands if epic-specific tests are needed"
    echo "  4. Add any epic-specific guidance to the 'extra' fields"
    echo ""
    echo "To use this prompt pack:"
    echo "  /broadcast-pack set roundtable-$EPIC_NAME"
    echo "  /broadcast-targeted (draft)"
    echo "  /broadcast-apply"
else
    log_error "Failed to create prompt pack"
    exit 1
fi
