#!/bin/bash
#
# Setup Cron Jobs for Maintenance Scripts
# Path: /root/projects/roundtable/scripts/maf/maintenance/setup-cron.sh
#
# Run once to install cron jobs

set -e

SCRIPT_DIR="/root/projects/roundtable/scripts/maf/maintenance"
TELEGRAM_ENV="/root/projects/roundtable/.agent-mail/telegram.env"

echo "=== Setting up maintenance cron jobs ==="

# Load Telegram credentials if available
if [[ -f "$TELEGRAM_ENV" ]]; then
    source "$TELEGRAM_ENV"
    echo "✓ Loaded Telegram credentials from telegram.env"
else
    echo "⚠ telegram.env not found - notifications will be limited"
fi

# Backup existing crontab
crontab -l > /tmp/crontab-backup-$(date +%Y%m%d_%H%M%S) 2>/dev/null || true

# Create new crontab with maintenance jobs
cat > /tmp/new-crontab << 'CRONTAB_EOF'
# MCP Agent Mail & Maintenance Cron Jobs
# Generated by setup-cron.sh - DO NOT EDIT MANUALLY
# Use ./setup-cron.sh to regenerate

# ============================================
# Disk Space Monitoring - Every 30 minutes
# ============================================
*/30 * * * * TELEGRAM_BOT_TOKEN="${TELEGRAM_BOT_TOKEN}" TELEGRAM_CHAT_ID="${TELEGRAM_CHAT_ID}" /root/projects/roundtable/scripts/maf/maintenance/check-disk.sh >/dev/null 2>&1

# ============================================
# Log Rotation & Cleanup - Daily at 2:30 AM
# ============================================
30 2 * * * TELEGRAM_BOT_TOKEN="${TELEGRAM_BOT_TOKEN}" TELEGRAM_CHAT_ID="${TELEGRAM_CHAT_ID}" /root/projects/roundtable/scripts/maf/maintenance/rotate-logs.sh >/dev/null 2>&1

# ============================================
# Test Telegram notification (runs once after setup)
# Uncomment to test:
# */5 * * * * TELEGRAM_BOT_TOKEN="${TELEGRAM_BOT_TOKEN}" TELEGRAM_CHAT_ID="${TELEGRAM_CHAT_ID}" /root/projects/roundtable/scripts/maf/maintenance/rotate-logs.sh >/dev/null 2>&1
CRONTAB_EOF

# Substitute actual Telegram credentials if available
if [[ -n "$TELEGRAM_BOT_TOKEN" && -n "$TELEGRAM_CHAT_ID" ]]; then
    sed -i "s|\${TELEGRAM_BOT_TOKEN}|${TELEGRAM_BOT_TOKEN}|g" /tmp/new-crontab
    sed -i "s|\${TELEGRAM_CHAT_ID}|${TELEGRAM_CHAT_ID}|g" /tmp/new-crontab
    echo "✓ Configured Telegram notifications"
fi

# Install new crontab
crontab /tmp/new-crontab
rm /tmp/new-crontab

echo ""
echo "✓ Cron jobs installed successfully!"
echo ""
echo "Installed cron jobs:"
crontab -l | grep -v "^#" | grep -v "^$"
echo ""
echo "To test Telegram notifications immediately:"
echo "  TELEGRAM_BOT_TOKEN=\"\$TELEGRAM_BOT_TOKEN\" \\"
echo "  TELEGRAM_CHAT_ID=\"\$TELEGRAM_CHAT_ID\" \\"
echo "  $SCRIPT_DIR/rotate-logs.sh"
echo ""

# Send test notification to Telegram
if [[ -n "$TELEGRAM_BOT_TOKEN" && -n "$TELEGRAM_CHAT_ID" ]]; then
    echo "Sending test notification to Telegram..."
    curl -s -X POST \
        "https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage" \
        -d "chat_id=${TELEGRAM_CHAT_ID}" \
        -d "text=✅ *Maintenance Cron Jobs Installed*

🤖 *Scheduled Tasks:*
• Disk monitoring: Every 30 minutes
• Log rotation: Daily at 2:30 AM

📁 *Scripts Location:*
$SCRIPT_DIR/

⏰ Installed at: $(date '+%Y-%m-%d %H:%M:%S')" \
        -d "parse_mode=Markdown" >/dev/null 2>&1 && echo "✓ Test notification sent!" || echo "⚠ Failed to send test notification"
fi

echo ""
echo "Done! Maintenance scripts are now active."
